version: "3.5"

services:
  zoox_db:
    image: mongo
    container_name: mongo-zoox    
    ports:
      - 27017:27017
    expose:
      - 27017      
    restart: always

  backend:
    image: back-zoox
    container_name: back-zoox
    build: ./backend    
    depends_on:
      - zoox_db
    ports:
      - 3535:3535

  frontend:
    image: front-zoox
    container_name: front-zoox
    build: ./frontend    
    ports:
      - 8080:8080            
    

    

 